2.12.1
Bib8/ashdi-spring-first-trial pull request #3
Opened 2022-03-12 19:43 UTC by Bib8

2022-03-13 16:39 UTC, madyar997 requested changes

2022-03-13 16:39 UTC, madyar997 commented on src/test/java/ashdi/com/ashdispringfirsttrial/CalcServiceImplTest.java
> +    public void shouldCompareExpectedResRFndActualResATestSumNegative(){
На все методы добавить аннотацию Test

2022-03-13 16:39 UTC, madyar997 commented on src/test/java/ashdi/com/ashdispringfirsttrial/CalcServiceImplTest.java
> +        Assert.assertEquals(THREE, out.multiplyResult(TWO, ONE));
Ожидаем 3 при умножении двойки на единицу. Исправить

2022-03-13 16:39 UTC, madyar997 commented on src/test/java/ashdi/com/ashdispringfirsttrial/CalcServiceImplTest.java
> +        Assert.assertEquals(THREE, out.divideResult(THREE, THREE));
Привести actual и expected значения к одному типу. При делении 3 на 3 ожидаем 3. Исправить

2022-03-13 16:39 UTC, madyar997 commented on src/test/java/ashdi/com/ashdispringfirsttrial/CalcServiceImplTest.java
> +        Assert.assertEquals(THREE, out.divideResult(THREE, NEGATIVE_THREE));
Привести actual и expected значения к одному типу

2022-03-13 16:39 UTC, madyar997 commented on src/test/java/ashdi/com/ashdispringfirsttrial/CalsServiceImplTestParam.java
> +    }
Этот тестовый метод лучше разбить на два отдельных метода
1) Проверяем просто деление
2) Проверяем выброс исключения

2022-03-14 03:24 UTC, Bib8 commented on src/test/java/ashdi/com/ashdispringfirsttrial/CalsServiceImplTestParam.java
> +    }
Здесь же только проверяется деление, про выброс исключения нет речи, для этого в параметрах, ноль не указан как делитель, т.е. поведение спрогнозировано

2022-03-14 03:31 UTC, merged